# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reservas.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ereservas.proto\x12\x08reservas\"Q\n\tSolicitud\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05phone\x18\x02 \x01(\t\x12\x12\n\nparty_size\x18\x03 \x01(\x05\x12\x13\n\x0bpreferences\x18\x04 \x01(\t\";\n\x0fReservasRequest\x12(\n\x0bsolicitudes\x18\x01 \x03(\x0b\x32\x13.reservas.Solicitud\"4\n\x10ReservasResponse\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\"\xb8\x01\n\x0bReservaInfo\x12\x16\n\x0ereservation_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05phone\x18\x03 \x01(\t\x12\x12\n\nparty_size\x18\x04 \x01(\x05\x12\x13\n\x0bpreferences\x18\x05 \x01(\t\x12\x10\n\x08table_id\x18\x06 \x03(\t\x12\x0e\n\x06status\x18\x07 \x01(\t\x12\x16\n\x0emesa_capacidad\x18\x08 \x01(\t\x12\x11\n\tmesa_tipo\x18\t \x01(\t\"4\n\x10RegistroResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\"(\n\x13NotificacionRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"5\n\x14NotificacionResponse\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\x12\x0c\n\x04tipo\x18\x02 \x01(\t2Y\n\x0eReservaService\x12G\n\x0e\x45nviarReservas\x12\x19.reservas.ReservasRequest\x1a\x1a.reservas.ReservasResponse2X\n\x0fRegistroService\x12\x45\n\x10RegistrarReserva\x12\x15.reservas.ReservaInfo\x1a\x1a.reservas.RegistroResponse2n\n\x10MonitoreoService\x12Z\n\x15RecibirNotificaciones\x12\x1d.reservas.NotificacionRequest\x1a\x1e.reservas.NotificacionResponse(\x01\x30\x01\x42\tZ\x07./protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reservas_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./proto'
  _globals['_SOLICITUD']._serialized_start=28
  _globals['_SOLICITUD']._serialized_end=109
  _globals['_RESERVASREQUEST']._serialized_start=111
  _globals['_RESERVASREQUEST']._serialized_end=170
  _globals['_RESERVASRESPONSE']._serialized_start=172
  _globals['_RESERVASRESPONSE']._serialized_end=224
  _globals['_RESERVAINFO']._serialized_start=227
  _globals['_RESERVAINFO']._serialized_end=411
  _globals['_REGISTRORESPONSE']._serialized_start=413
  _globals['_REGISTRORESPONSE']._serialized_end=465
  _globals['_NOTIFICACIONREQUEST']._serialized_start=467
  _globals['_NOTIFICACIONREQUEST']._serialized_end=507
  _globals['_NOTIFICACIONRESPONSE']._serialized_start=509
  _globals['_NOTIFICACIONRESPONSE']._serialized_end=562
  _globals['_RESERVASERVICE']._serialized_start=564
  _globals['_RESERVASERVICE']._serialized_end=653
  _globals['_REGISTROSERVICE']._serialized_start=655
  _globals['_REGISTROSERVICE']._serialized_end=743
  _globals['_MONITOREOSERVICE']._serialized_start=745
  _globals['_MONITOREOSERVICE']._serialized_end=855
# @@protoc_insertion_point(module_scope)
