// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: reservas.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mensajes
type Solicitud struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	PartySize     int32                  `protobuf:"varint,3,opt,name=party_size,json=partySize,proto3" json:"party_size,omitempty"`
	Preferences   string                 `protobuf:"bytes,4,opt,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Solicitud) Reset() {
	*x = Solicitud{}
	mi := &file_reservas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Solicitud) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Solicitud) ProtoMessage() {}

func (x *Solicitud) ProtoReflect() protoreflect.Message {
	mi := &file_reservas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Solicitud.ProtoReflect.Descriptor instead.
func (*Solicitud) Descriptor() ([]byte, []int) {
	return file_reservas_proto_rawDescGZIP(), []int{0}
}

func (x *Solicitud) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Solicitud) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Solicitud) GetPartySize() int32 {
	if x != nil {
		return x.PartySize
	}
	return 0
}

func (x *Solicitud) GetPreferences() string {
	if x != nil {
		return x.Preferences
	}
	return ""
}

type ReservasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Solicitudes   []*Solicitud           `protobuf:"bytes,1,rep,name=solicitudes,proto3" json:"solicitudes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservasRequest) Reset() {
	*x = ReservasRequest{}
	mi := &file_reservas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservasRequest) ProtoMessage() {}

func (x *ReservasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservasRequest.ProtoReflect.Descriptor instead.
func (*ReservasRequest) Descriptor() ([]byte, []int) {
	return file_reservas_proto_rawDescGZIP(), []int{1}
}

func (x *ReservasRequest) GetSolicitudes() []*Solicitud {
	if x != nil {
		return x.Solicitudes
	}
	return nil
}

type ReservasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensaje       string                 `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservasResponse) Reset() {
	*x = ReservasResponse{}
	mi := &file_reservas_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservasResponse) ProtoMessage() {}

func (x *ReservasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservas_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservasResponse.ProtoReflect.Descriptor instead.
func (*ReservasResponse) Descriptor() ([]byte, []int) {
	return file_reservas_proto_rawDescGZIP(), []int{2}
}

func (x *ReservasResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *ReservasResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ReservaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	PartySize     int32                  `protobuf:"varint,4,opt,name=party_size,json=partySize,proto3" json:"party_size,omitempty"`
	Preferences   string                 `protobuf:"bytes,5,opt,name=preferences,proto3" json:"preferences,omitempty"`
	TableId       []string               `protobuf:"bytes,6,rep,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	MesaCapacidad string                 `protobuf:"bytes,8,opt,name=mesa_capacidad,json=mesaCapacidad,proto3" json:"mesa_capacidad,omitempty"`
	MesaTipo      string                 `protobuf:"bytes,9,opt,name=mesa_tipo,json=mesaTipo,proto3" json:"mesa_tipo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservaInfo) Reset() {
	*x = ReservaInfo{}
	mi := &file_reservas_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservaInfo) ProtoMessage() {}

func (x *ReservaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_reservas_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservaInfo.ProtoReflect.Descriptor instead.
func (*ReservaInfo) Descriptor() ([]byte, []int) {
	return file_reservas_proto_rawDescGZIP(), []int{3}
}

func (x *ReservaInfo) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReservaInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReservaInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ReservaInfo) GetPartySize() int32 {
	if x != nil {
		return x.PartySize
	}
	return 0
}

func (x *ReservaInfo) GetPreferences() string {
	if x != nil {
		return x.Preferences
	}
	return ""
}

func (x *ReservaInfo) GetTableId() []string {
	if x != nil {
		return x.TableId
	}
	return nil
}

func (x *ReservaInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReservaInfo) GetMesaCapacidad() string {
	if x != nil {
		return x.MesaCapacidad
	}
	return ""
}

func (x *ReservaInfo) GetMesaTipo() string {
	if x != nil {
		return x.MesaTipo
	}
	return ""
}

type RegistroResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistroResponse) Reset() {
	*x = RegistroResponse{}
	mi := &file_reservas_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistroResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistroResponse) ProtoMessage() {}

func (x *RegistroResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservas_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistroResponse.ProtoReflect.Descriptor instead.
func (*RegistroResponse) Descriptor() ([]byte, []int) {
	return file_reservas_proto_rawDescGZIP(), []int{4}
}

func (x *RegistroResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegistroResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type NotificacionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificacionRequest) Reset() {
	*x = NotificacionRequest{}
	mi := &file_reservas_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificacionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificacionRequest) ProtoMessage() {}

func (x *NotificacionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservas_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificacionRequest.ProtoReflect.Descriptor instead.
func (*NotificacionRequest) Descriptor() ([]byte, []int) {
	return file_reservas_proto_rawDescGZIP(), []int{5}
}

func (x *NotificacionRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type NotificacionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensaje       string                 `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Tipo          string                 `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"` // "exitosa", "modificada", "fallida"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificacionResponse) Reset() {
	*x = NotificacionResponse{}
	mi := &file_reservas_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificacionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificacionResponse) ProtoMessage() {}

func (x *NotificacionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservas_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificacionResponse.ProtoReflect.Descriptor instead.
func (*NotificacionResponse) Descriptor() ([]byte, []int) {
	return file_reservas_proto_rawDescGZIP(), []int{6}
}

func (x *NotificacionResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *NotificacionResponse) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

var File_reservas_proto protoreflect.FileDescriptor

const file_reservas_proto_rawDesc = "" +
	"\n" +
	"\x0ereservas.proto\x12\breservas\"v\n" +
	"\tSolicitud\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"party_size\x18\x03 \x01(\x05R\tpartySize\x12 \n" +
	"\vpreferences\x18\x04 \x01(\tR\vpreferences\"H\n" +
	"\x0fReservasRequest\x125\n" +
	"\vsolicitudes\x18\x01 \x03(\v2\x13.reservas.SolicitudR\vsolicitudes\"F\n" +
	"\x10ReservasResponse\x12\x18\n" +
	"\amensaje\x18\x01 \x01(\tR\amensaje\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\x96\x02\n" +
	"\vReservaInfo\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"party_size\x18\x04 \x01(\x05R\tpartySize\x12 \n" +
	"\vpreferences\x18\x05 \x01(\tR\vpreferences\x12\x19\n" +
	"\btable_id\x18\x06 \x03(\tR\atableId\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12%\n" +
	"\x0emesa_capacidad\x18\b \x01(\tR\rmesaCapacidad\x12\x1b\n" +
	"\tmesa_tipo\x18\t \x01(\tR\bmesaTipo\"F\n" +
	"\x10RegistroResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\"2\n" +
	"\x13NotificacionRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"D\n" +
	"\x14NotificacionResponse\x12\x18\n" +
	"\amensaje\x18\x01 \x01(\tR\amensaje\x12\x12\n" +
	"\x04tipo\x18\x02 \x01(\tR\x04tipo2Y\n" +
	"\x0eReservaService\x12G\n" +
	"\x0eEnviarReservas\x12\x19.reservas.ReservasRequest\x1a\x1a.reservas.ReservasResponse2X\n" +
	"\x0fRegistroService\x12E\n" +
	"\x10RegistrarReserva\x12\x15.reservas.ReservaInfo\x1a\x1a.reservas.RegistroResponse2n\n" +
	"\x10MonitoreoService\x12Z\n" +
	"\x15RecibirNotificaciones\x12\x1d.reservas.NotificacionRequest\x1a\x1e.reservas.NotificacionResponse(\x010\x01B\tZ\a./protob\x06proto3"

var (
	file_reservas_proto_rawDescOnce sync.Once
	file_reservas_proto_rawDescData []byte
)

func file_reservas_proto_rawDescGZIP() []byte {
	file_reservas_proto_rawDescOnce.Do(func() {
		file_reservas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reservas_proto_rawDesc), len(file_reservas_proto_rawDesc)))
	})
	return file_reservas_proto_rawDescData
}

var file_reservas_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_reservas_proto_goTypes = []any{
	(*Solicitud)(nil),            // 0: reservas.Solicitud
	(*ReservasRequest)(nil),      // 1: reservas.ReservasRequest
	(*ReservasResponse)(nil),     // 2: reservas.ReservasResponse
	(*ReservaInfo)(nil),          // 3: reservas.ReservaInfo
	(*RegistroResponse)(nil),     // 4: reservas.RegistroResponse
	(*NotificacionRequest)(nil),  // 5: reservas.NotificacionRequest
	(*NotificacionResponse)(nil), // 6: reservas.NotificacionResponse
}
var file_reservas_proto_depIdxs = []int32{
	0, // 0: reservas.ReservasRequest.solicitudes:type_name -> reservas.Solicitud
	1, // 1: reservas.ReservaService.EnviarReservas:input_type -> reservas.ReservasRequest
	3, // 2: reservas.RegistroService.RegistrarReserva:input_type -> reservas.ReservaInfo
	5, // 3: reservas.MonitoreoService.RecibirNotificaciones:input_type -> reservas.NotificacionRequest
	2, // 4: reservas.ReservaService.EnviarReservas:output_type -> reservas.ReservasResponse
	4, // 5: reservas.RegistroService.RegistrarReserva:output_type -> reservas.RegistroResponse
	6, // 6: reservas.MonitoreoService.RecibirNotificaciones:output_type -> reservas.NotificacionResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_reservas_proto_init() }
func file_reservas_proto_init() {
	if File_reservas_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reservas_proto_rawDesc), len(file_reservas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_reservas_proto_goTypes,
		DependencyIndexes: file_reservas_proto_depIdxs,
		MessageInfos:      file_reservas_proto_msgTypes,
	}.Build()
	File_reservas_proto = out.File
	file_reservas_proto_goTypes = nil
	file_reservas_proto_depIdxs = nil
}
