// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.12.4
// source: proto/reservas.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mensajes
type Solicitud struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone       string `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	PartySize   int32  `protobuf:"varint,3,opt,name=party_size,json=partySize,proto3" json:"party_size,omitempty"`
	Preferences string `protobuf:"bytes,4,opt,name=preferences,proto3" json:"preferences,omitempty"`
}

func (x *Solicitud) Reset() {
	*x = Solicitud{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reservas_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Solicitud) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Solicitud) ProtoMessage() {}

func (x *Solicitud) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservas_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Solicitud.ProtoReflect.Descriptor instead.
func (*Solicitud) Descriptor() ([]byte, []int) {
	return file_proto_reservas_proto_rawDescGZIP(), []int{0}
}

func (x *Solicitud) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Solicitud) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Solicitud) GetPartySize() int32 {
	if x != nil {
		return x.PartySize
	}
	return 0
}

func (x *Solicitud) GetPreferences() string {
	if x != nil {
		return x.Preferences
	}
	return ""
}

type ReservasRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Solicitudes []*Solicitud `protobuf:"bytes,1,rep,name=solicitudes,proto3" json:"solicitudes,omitempty"`
}

func (x *ReservasRequest) Reset() {
	*x = ReservasRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reservas_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReservasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservasRequest) ProtoMessage() {}

func (x *ReservasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservas_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservasRequest.ProtoReflect.Descriptor instead.
func (*ReservasRequest) Descriptor() ([]byte, []int) {
	return file_proto_reservas_proto_rawDescGZIP(), []int{1}
}

func (x *ReservasRequest) GetSolicitudes() []*Solicitud {
	if x != nil {
		return x.Solicitudes
	}
	return nil
}

type ReservasResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mensaje string `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ReservasResponse) Reset() {
	*x = ReservasResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reservas_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReservasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservasResponse) ProtoMessage() {}

func (x *ReservasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservas_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservasResponse.ProtoReflect.Descriptor instead.
func (*ReservasResponse) Descriptor() ([]byte, []int) {
	return file_proto_reservas_proto_rawDescGZIP(), []int{2}
}

func (x *ReservasResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *ReservasResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ReservaInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReservationId string   `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Name          string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	PartySize     int32    `protobuf:"varint,4,opt,name=party_size,json=partySize,proto3" json:"party_size,omitempty"`
	Preferences   string   `protobuf:"bytes,5,opt,name=preferences,proto3" json:"preferences,omitempty"`
	TableId       []string `protobuf:"bytes,6,rep,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	Status        string   `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	MesaCapacidad string   `protobuf:"bytes,8,opt,name=mesa_capacidad,json=mesaCapacidad,proto3" json:"mesa_capacidad,omitempty"`
	MesaTipo      string   `protobuf:"bytes,9,opt,name=mesa_tipo,json=mesaTipo,proto3" json:"mesa_tipo,omitempty"`
}

func (x *ReservaInfo) Reset() {
	*x = ReservaInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reservas_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReservaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservaInfo) ProtoMessage() {}

func (x *ReservaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservas_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservaInfo.ProtoReflect.Descriptor instead.
func (*ReservaInfo) Descriptor() ([]byte, []int) {
	return file_proto_reservas_proto_rawDescGZIP(), []int{3}
}

func (x *ReservaInfo) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReservaInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReservaInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ReservaInfo) GetPartySize() int32 {
	if x != nil {
		return x.PartySize
	}
	return 0
}

func (x *ReservaInfo) GetPreferences() string {
	if x != nil {
		return x.Preferences
	}
	return ""
}

func (x *ReservaInfo) GetTableId() []string {
	if x != nil {
		return x.TableId
	}
	return nil
}

func (x *ReservaInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReservaInfo) GetMesaCapacidad() string {
	if x != nil {
		return x.MesaCapacidad
	}
	return ""
}

func (x *ReservaInfo) GetMesaTipo() string {
	if x != nil {
		return x.MesaTipo
	}
	return ""
}

type RegistroResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Mensaje string `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
}

func (x *RegistroResponse) Reset() {
	*x = RegistroResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reservas_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistroResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistroResponse) ProtoMessage() {}

func (x *RegistroResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservas_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistroResponse.ProtoReflect.Descriptor instead.
func (*RegistroResponse) Descriptor() ([]byte, []int) {
	return file_proto_reservas_proto_rawDescGZIP(), []int{4}
}

func (x *RegistroResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegistroResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type NotificacionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (x *NotificacionRequest) Reset() {
	*x = NotificacionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reservas_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotificacionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificacionRequest) ProtoMessage() {}

func (x *NotificacionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservas_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificacionRequest.ProtoReflect.Descriptor instead.
func (*NotificacionRequest) Descriptor() ([]byte, []int) {
	return file_proto_reservas_proto_rawDescGZIP(), []int{5}
}

func (x *NotificacionRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type NotificacionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mensaje string `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Tipo    string `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"` // "exitosa", "modificada", "fallida"
}

func (x *NotificacionResponse) Reset() {
	*x = NotificacionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reservas_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotificacionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificacionResponse) ProtoMessage() {}

func (x *NotificacionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservas_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificacionResponse.ProtoReflect.Descriptor instead.
func (*NotificacionResponse) Descriptor() ([]byte, []int) {
	return file_proto_reservas_proto_rawDescGZIP(), []int{6}
}

func (x *NotificacionResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *NotificacionResponse) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

var File_proto_reservas_proto protoreflect.FileDescriptor

var file_proto_reservas_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x73,
	0x22, 0x76, 0x0a, 0x09, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x74, 0x79,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x61, 0x72,
	0x74, 0x79, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x22, 0x48, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x61, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x0b, 0x73,
	0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x73, 0x2e, 0x53, 0x6f, 0x6c, 0x69,
	0x63, 0x69, 0x74, 0x75, 0x64, 0x52, 0x0b, 0x73, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x73, 0x22, 0x46, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x96, 0x02, 0x0a, 0x0b, 0x52,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70,
	0x61, 0x72, 0x74, 0x79, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x70, 0x61, 0x72, 0x74, 0x79, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x08,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x25, 0x0a, 0x0e, 0x6d, 0x65, 0x73, 0x61, 0x5f, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x64, 0x61,
	0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6d, 0x65, 0x73, 0x61, 0x43, 0x61, 0x70,
	0x61, 0x63, 0x69, 0x64, 0x61, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x73, 0x61, 0x5f, 0x74,
	0x69, 0x70, 0x6f, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x61, 0x54,
	0x69, 0x70, 0x6f, 0x22, 0x46, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x22, 0x32, 0x0a, 0x13, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22,
	0x44, 0x0a, 0x14, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61,
	0x6a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x69, 0x70, 0x6f, 0x32, 0x59, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x0e, 0x45, 0x6e, 0x76, 0x69, 0x61,
	0x72, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x73, 0x12, 0x19, 0x2e, 0x72, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x61, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x73, 0x2e,
	0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x32, 0x58, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72,
	0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x12, 0x15, 0x2e, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x61, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x1a,
	0x2e, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x73, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x6e, 0x0a, 0x10, 0x4d, 0x6f,
	0x6e, 0x69, 0x74, 0x6f, 0x72, 0x65, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5a,
	0x0a, 0x15, 0x52, 0x65, 0x63, 0x69, 0x62, 0x69, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x63, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x12, 0x1d, 0x2e, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x61, 0x73, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61,
	0x73, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_reservas_proto_rawDescOnce sync.Once
	file_proto_reservas_proto_rawDescData = file_proto_reservas_proto_rawDesc
)

func file_proto_reservas_proto_rawDescGZIP() []byte {
	file_proto_reservas_proto_rawDescOnce.Do(func() {
		file_proto_reservas_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_reservas_proto_rawDescData)
	})
	return file_proto_reservas_proto_rawDescData
}

var file_proto_reservas_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_reservas_proto_goTypes = []interface{}{
	(*Solicitud)(nil),            // 0: reservas.Solicitud
	(*ReservasRequest)(nil),      // 1: reservas.ReservasRequest
	(*ReservasResponse)(nil),     // 2: reservas.ReservasResponse
	(*ReservaInfo)(nil),          // 3: reservas.ReservaInfo
	(*RegistroResponse)(nil),     // 4: reservas.RegistroResponse
	(*NotificacionRequest)(nil),  // 5: reservas.NotificacionRequest
	(*NotificacionResponse)(nil), // 6: reservas.NotificacionResponse
}
var file_proto_reservas_proto_depIdxs = []int32{
	0, // 0: reservas.ReservasRequest.solicitudes:type_name -> reservas.Solicitud
	1, // 1: reservas.ReservaService.EnviarReservas:input_type -> reservas.ReservasRequest
	3, // 2: reservas.RegistroService.RegistrarReserva:input_type -> reservas.ReservaInfo
	5, // 3: reservas.MonitoreoService.RecibirNotificaciones:input_type -> reservas.NotificacionRequest
	2, // 4: reservas.ReservaService.EnviarReservas:output_type -> reservas.ReservasResponse
	4, // 5: reservas.RegistroService.RegistrarReserva:output_type -> reservas.RegistroResponse
	6, // 6: reservas.MonitoreoService.RecibirNotificaciones:output_type -> reservas.NotificacionResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_reservas_proto_init() }
func file_proto_reservas_proto_init() {
	if File_proto_reservas_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_reservas_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Solicitud); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reservas_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReservasRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reservas_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReservasResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reservas_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReservaInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reservas_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistroResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reservas_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotificacionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reservas_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotificacionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_reservas_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_reservas_proto_goTypes,
		DependencyIndexes: file_proto_reservas_proto_depIdxs,
		MessageInfos:      file_proto_reservas_proto_msgTypes,
	}.Build()
	File_proto_reservas_proto = out.File
	file_proto_reservas_proto_rawDesc = nil
	file_proto_reservas_proto_goTypes = nil
	file_proto_reservas_proto_depIdxs = nil
}
